name: Build

on:
  push:
    branches:
      - main
      - dev
      - release-*
      - feat-*
      - ci-*
      - refactor-*
      - fix-*
      - test-*
    paths:
      - '.github/workflows/build.yml'
      - '**/Cargo.toml'
      - '**/*.rs'
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v5

      - name: Install Rust-nightly
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy

      - name: Run clippy
        run: |
          cargo +nightly clippy --version
          cargo +nightly clippy --all-features -- -D warnings

      - name: Run fmt
        run: |
          cargo +nightly fmt --all -- --check

  build_macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, macos-15]
        rust: [1.90.0]
    steps:
      - name: Clone project
        id: checkout
        uses: actions/checkout@v5

      - name: Install Rust-stable
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}

      - name: Build
        run: |
          cargo build --release --verbose

  build_linux:
    runs-on: ${{ matrix.runner }}
    container:
      image: ${{ matrix.image }}
    strategy:
      matrix:
        build: [linux-x86_64, linux-aarch64]
        include:
          - build: linux-x86_64
            runner: ubuntu-latest
            image: ubuntu:20.04
            target: x86_64-unknown-linux-gnu
          - build: linux-aarch64
            runner: ubuntu-24.04-arm
            image: arm64v8/ubuntu:20.04
            target: aarch64-unknown-linux-gnu
        rust: [1.90.0]
      fail-fast: false

    steps:
      - name: Clone project
        id: checkout
        uses: actions/checkout@v5

      - name: Install dependencies silently
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt update && apt install -y curl build-essential pkg-config

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}

      - name: Build
        run: |
          cargo build --release --verbose --target ${{ matrix.target }}
